### PR TITLE
Fix/duplicate files

### LINKED ISSUE #85: File upload does not properly check on duplicates
Image for reference
afbeelding

### PR DESCRIPTION
**Pull request by G4mingEdition**

### CODE REVIEW

File: src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx [hunk 1]
```diff
@@ -133,6 +133,7 @@ const FileDropZone = (props: DropZoneProps) => {
      * with the props.
      */
     const onDrop = React.useCallback((acceptedFiles: Array<File>) => {
+        console.log(acceptedFiles);
```
Comment (FreekDS) [inline src/renderer/components/FileCheckDropzone/FileCheckDropzone.tsx]: Console log can be removed

File: src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx [hunk 2]
```diff
@@ -130,9 +130,28 @@ const Stage1 = (props: Stage1Props) => {
...
+                    if(file.path === inputFile.path) {
+                        const index = fileList.indexOf(inputFile);
+                        fileList.splice(index, 1);
+                        found = true;
+                    }
+                    i++;
+                }
+            });
+
+            console.log(fileList);
```
Comment (FreekDS) [inline src/renderer/components/FileUploadStages/PickFiles/Stage1.tsx]: Same here

**Review by FreekDS — CHANGES_REQUESTED** [review]

**Review by AmberPerard — APPROVED** [review]

**Review by AmberPerard — APPROVED** [review]

**Review by FreekDS — APPROVED** [review]
